### ISSUE TITLE
Is it possible to label the length, width and height of an object based on this 3d box?

### ISSUE THREAD

**Issue by upper127** [bharath5673/YOLOv8-3D#10]
This 3d box is derived from the 2d box, so does this 3d box imply some real information about the size of the object

**Comment by bharath5673** [comment]
yes, the 3D frame can indeed provide information about the size of objects
in the scene..

**Comment by upper127** [comment]
If I want to display the dimensions such as length, width, etc. of an object in the code you posted, how do I make the change? Can you provide some help?

**Comment by bharath5673** [comment]
Change ?? Like how?

**Comment by upper127** [comment]
Display the object's length, width, and height on the final recognition.

**Comment by upper127** [comment]
![image](https://github.com/bharath5673/YOLOv8-3D/assets/95669608/e1b894d3-9129-4aca-9565-9b520d5818ff)
Also, why is this 3d box tilted for me

**Comment by bharath5673** [comment]
> Display the object's length, width, and height on the final recognition.

once u got all the coordinate pts, calculate euclidean dist between all each pts, establish a scale factor that maps pixel measurements to real-world measurements doing camera calibrations,  apply recale factors if required, and then display..

**Comment by bharath5673** [comment]
> ![image](https://private-user-images.githubusercontent.com/95669608/314923253-e1b894d3-9129-4aca-9565-9b520d5818ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMDA2MjcsIm5iZiI6MTcxMTAwMDMyNywicGF0aCI6Ii85NTY2OTYwOC8zMTQ5MjMyNTMtZTFiODk0ZDMtOTEyOS00YWNhLTk1NjUtOWI1MjBkNTgxOGZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDA1NTIwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5MDQwNjM5ZDRhMDM4NTBlYjM2ZDdmOWJhNTAyZjY4ODk5ZTZkYjVmYjllNzZmYmUwZmI1YzFkODU5NTk4YWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.__8hxU0FvQ8t8i6-clqLslW0zPJqsKsrzaXHJ4aGCsw) Also, why is this 3d box tilted for me

model is failing to generalize..

**Comment by upper127** [comment]
> > ![image](https://private-user-images.githubusercontent.com/95669608/314923253-e1b894d3-9129-4aca-9565-9b520d5818ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMDA2MjcsIm5iZiI6MTcxMTAwMDMyNywicGF0aCI6Ii85NTY2OTYwOC8zMTQ5MjMyNTMtZTFiODk0ZDMtOTEyOS00YWNhLTk1NjUtOWI1MjBkNTgxOGZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDA1NTIwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5MDQwNjM5ZDRhMDM4NTBlYjM2ZDdmOWJhNTAyZjY4ODk5ZTZkYjVmYjllNzZmYmUwZmI1YzFkODU5NTk4YWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.__8hxU0FvQ8t8i6-clqLslW0zPJqsKsrzaXHJ4aGCsw)另外，为什么这个 3d 盒子对我来说是倾斜的
> 
> 模型无法泛化。.
But I'm using the test data you provided.
Can you provide more models and pre-weights, I don't seem to see all of them in github（resnet、efficientnet、vgg）

**Comment by upper127** [comment]
> > Display the object's length, width, and height on the final recognition.
> 
> once u got all the coordinate pts, calculate euclidean dist between all each pts, establish a scale factor that maps pixel measurements to real-world measurements doing camera calibrations, apply recale factors if required, and then display..
Since I'm adding functionality based on the code you posted, in the original code I seem to see the ability to convert 2d vehicle images into 3d information
code：        dim = [prediction[0][0]]

Is it implied here that the model's estimate of the size of the object？
Based on your answer, I don't quite understand this recale factors

**Comment by bharath5673** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/95669608/314923253-e1b894d3-9129-4aca-9565-9b520d5818ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMDA2MjcsIm5iZiI6MTcxMTAwMDMyNywicGF0aCI6Ii85NTY2OTYwOC8zMTQ5MjMyNTMtZTFiODk0ZDMtOTEyOS00YWNhLTk1NjUtOWI1MjBkNTgxOGZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDA1NTIwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5MDQwNjM5ZDRhMDM4NTBlYjM2ZDdmOWJhNTAyZjY4ODk5ZTZkYjVmYjllNzZmYmUwZmI1YzFkODU5NTk4YWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.__8hxU0FvQ8t8i6-clqLslW0zPJqsKsrzaXHJ4aGCsw)另外，为什么这个 3d 盒子对我来说是倾斜的
> > 
> > 
> > 模型无法泛化。.
> > But I'm using the test data you provided.
> > Can you provide more models and pre-weights, I don't seem to see all of them in github（resnet、efficientnet、vgg）

I'm sorry, but training the code to generate weights is a necessary step.
There isn't an alternative method available at the moment. If you encounter
any difficulties during the training process, feel free to ask for
assistance.

**Comment by bharath5673** [comment]
> > > Display the object's length, width, and height on the final recognition.
> > 
> > 
> > once u got all the coordinate pts, calculate euclidean dist between all each pts, establish a scale factor that maps pixel measurements to real-world measurements doing camera calibrations, apply recale factors if required, and then display..
> > Since I'm adding functionality based on the code you posted, in the original code I seem to see the ability to convert 2d vehicle images into 3d information
> > code：        dim = [prediction[0][0]]
> 
> Is it implied here that the model's estimate of the size of the object？ Based on your answer, I don't quite understand this recale factors

no,, its not.. //  rescale is to use the established scale factor or apply scale factor to convert pixel measurements of objects in the image to real-world measurements., This involves multiplying the pixel measurements by the appropriate scale factor to obtain lengths, widths, and heights in real-world units..

**Comment by upper127** [comment]
Do you mean that I should determine the proportionality between the pixel size and the actual size, and then multiply the pixel size predicted by the model by this proportionality to arrive at the size of the actual object?

**Comment by bharath5673** [comment]
Exactly! You've got it..

**Comment by upper127** [comment]
But now there is a problem: I want to implement the estimation of the real size on the code and raw data you provided first. According to the scenario we discussed above, it seems that there is no way to construct the ratio of the true size to the pixel size for the time being, unless I construct a specialized data myself



> Exactly! You've got it..

**Comment by KAIT-Aekanan** [comment]
@upper127 How did you get it to output a dimension? Is there a way I could get some hint of the code about it?
