### ISSUE TITLE
Problems with executing demo.py

### ISSUE THREAD

**Issue by TJW-XMUT** [bharath5673/YOLOv8-3D#2]
Where can I get weights with the suffix "_weights.h5"? I download this weight and run demo.py with "ValueError: No model config found in the file at <tensorflow.python.platform.gfile.GFile object at 0x00000163B1C45CD0>.” How to solve it? Thank you very much for your reply. Thank you.

**Comment by bharath5673** [comment]
no u cant get '_weights.h5' this weights// u have to use train.py to to train and save weights (eg: '{model_name}_weights.h5') and then u can use it.. ty))

**Comment by TJW-XMUT** [comment]
My device can't train the code. Can you provide me with trained weights that can be called directly? Thank you very much.

**Comment by bharath5673** [comment]
I'm sorry, but training the code to generate weights is a necessary step.
There isn't an alternative method available at the moment. If you encounter
any difficulties during the training process, feel free to ask for
assistance.
