### ISSUE TITLE
Pretrained weights and more training details please?

### ISSUE THREAD

**Issue by jerinka** [bharath5673/YOLOv8-3D#4]
Hi this repo looks interesting. Could you please provide pretrained weights and some sample data to run inference please. Also please add some more details of training, like what data to be downloaded from kitti, I see multiple links there. What is the folder structure needed?

**Comment by bharath5673** [comment]
for training data links:
`https://s3.eu-central-1.amazonaws.com/avg-kitti/data_object_image_2.zip`
`https://s3.eu-central-1.amazonaws.com/avg-kitti/data_object_label_2.zip`

and for [folder structure](https://github.com/bharath5673/YOLOv8-3D/blob/23264ab5803f6bac8a423175f0083143c39e13d5/train.py#L61)
